### ISSUE TITLE
[ZF3] [RFC] Removal of `get([A-Z][A-Za-z]+)Config` methods from modules

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zendframework#5288]
This is an RFC for a simplification that would help a lot in building ZF applications considering non-cacheable configurations.

## Problem

Some configurations rely on closures, service instances and generally non-serializable data that may break the application when config is merged and then cached

## Current solution (ZF2)

In order to solve the problem, ZF2 introduced a series of interfaces that allow developers can implement in their `Module` classes to add configured services programmatically:

 * `Zend\ModuleManager\Feature\ControllerPluginProviderInterface`
 * `Zend\ModuleManager\Feature\ControllerProviderInterface`
 * `Zend\ModuleManager\Feature\FilterProviderInterface`
 * `Zend\ModuleManager\Feature\FormElementProviderInterface`
 * `Zend\ModuleManager\Feature\HydratorProviderInterface`
 * `Zend\ModuleManager\Feature\InputFilterProviderInterface`
 * `Zend\ModuleManager\Feature\RouteProviderInterface`
 * `Zend\ModuleManager\Feature\SerializerProviderInterface`
 * `Zend\ModuleManager\Feature\ServiceProviderInterface`
 * `Zend\ModuleManager\Feature\ValidatorProviderInterface`
 * `Zend\ModuleManager\Feature\ViewHelperProviderInterface`

These configurations basically merge data to the already merged config _AFTER_ it is cached. They all act in the same way, just with different naming and providing different config keys. That's a lot of duplicated code, triggered events and inconsistencies. Additionally, we never suggest usage of those methods if not strictly needed, which makes their existence very confusing for those who don't know that.

## Suggestion (ZF3)

I hereby suggest removing (deprecating?) all the interfaces mentioned above, and instead introduce something like `Zend\ModuleManager\Feature\UnCacheableConfigProviderInterface` (suggestions on the name, please!):

```php
namespace Example;

use Zend\ModuleManager\Feature\ConfigProviderInterface;
use Zend\ModuleManager\Feature\UnCacheableConfigProviderInterface;

class Module implements ConfigProviderInterface, UnCacheableConfigProviderInterface
{
    public function getConfig()
    {
        return [/* like before, nothing to see here! */];
    }

    public function getUnCacheableConfig()
    {
        return [
            // replaces `getViewHelperConfig()`
            'view_helpers' => [
                'services' => ['foo' => new SomeHelper()],
                'factories' => [
                    'bar' => function () {/* can't cache this! */},
                ],
            ],
        ];
    }
}
```

#### Bonus

With this approach, we can also get rid of `Zend\ModuleManager\Feature\LocatorRegisteredInterface`, which allows us to have modules like [`EdpMarkdown`](https://github.com/EvanDotPro/EdpMarkdown/blob/a61cb4fc49efbd5c4285ba46a5286bfc78b0c938/Module.php) register the module as a service:

```php
namespace Example;

use Zend\ModuleManager\Feature\UnCacheableConfigProviderInterface;

class Module implements UnCacheableConfigProviderInterface
{
    public function getUnCacheableConfig()
    {
        return [
            'service_manager' => [
                'services' => [__CLASS__ => $this],
            ],
        ];
    }
}
```

## Benefits

 * we get rid of a lot of triggered events during module loading
 * we get rid of a lot of documentation related to those `get([A-Z][A-Za-z]+)Config` methods
 * we get rid of `Zend\ModuleManager\Feature\LocatorRegisteredInterface`
 * we get a minor performance improvement
 * we get a clear understanding of what `getUnCacheableConfig` does. The name says it for itself
 * we don't need to add more methods in case more plugin managers are added in future

## ZF2 BC compatibility

In order to keep BC with ZF2, we can create a `Zend\ModuleManager\Listener\Zf2CompatibilityListener`, which emulates the same logic of all the current `get([A-Z][A-Za-z]+)Config` methods. It can be either on by default or opt-in, but that has to be decided

## Drawbacks

None so far

## TODO

 - [x] discuss naming of `getUnCacheableConfig`
 - [x] discuss naming of `Zend\ModuleManager\Feature\UnCacheableConfigProviderInterface`
 - [x] find possible drawbacks
 - [x] get positive or negative feedback (**positive** feedback gained)
 - [x] discuss `Zend\ModuleManager\Listener\Zf2CompatibilityListener` being turned on or off by default
 - [ ] provide pull request

## Conclusions

 - `get([A-Z][A-Za-z]+)Config` will be removed from the module classes. `getConfig` will be used
 - Using un-cacheable config will simply be penalized, avoid that. That's it, nothing more
 - We will simply build a listener that verifies if config can be cached safely before attempting caching. That would allow us to throw meaningful exceptions
 - We will provide a listener for ZF2.x compatibility, so that `get([A-Z][A-Za-z]+)Config` can still be used

That's it, only removal of of methods, and that's perfectly fine. I'll work on a PR as soon as possible.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
