### ISSUE TITLE
[ZF3] [RFC] Embracing stateless/immutable state

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zendframework#5599]
## ZF's slowness and bootstrapping

The problem of ZF2's performance is mainly related with having a huge "bootstrap" step (loading modules, configuring the service manager, instantiating core services).

Today, I got back at looking at [`OcraHopHop`](https://github.com/Ocramius/OcraHopHop) after looking into @rdlowrey's amazing job in building [`Aerys`](https://gist.github.com/rdlowrey/b4f94f670a0b97ece845) (not yet released), which is basically the kickass nonblocking stuff of node.js minus the horror of javascript (that is my take on it, feel free to insult me :) ).

## Avoiding bootstrap

The idea is simple: run PHP without a web server as an own http service. Something like:

```sh
./run-my-application.php --port=80 &
```

This could work with any PHP application, as long as we embrace immutable state.

`OcraHopHop` worked fine with this concept, and I obtained impressive results with an 80% or faster ZF2 application, but there are some limitations related to state, which prevents asynchronous operations and eventually threading.

## What "stateless" means

For those who don't have a clear mind on what I mean, this is what a stateless application should look like:

```php
public function testApplicationIsStateless()
{
    $application = $this->bootstrapApplication();

    $application->run();
    
    $serialized = serialize($application);

    $application->run();

    $this->assertSame(
        $serialized,
        serialize($application),
        'Ensure that state in the application has not changed after the first run'
    );
}
```

This is just pseudo-code, and of course we cannot serialize an application since it contains un-serializable objects, but you get the point.

You can read up more about what I mean with "stateless" on @igorw's [blog](https://igor.io/2013/03/31/stateless-services.html)

## What the problem is

Try it for yourself! Try running `OcraHopHop` against the normal "Hello World" skeleton application example - it will slow down after a dozen requests, and the output will change at every request (more and more broken at every iteration).

That is because ZF2 internals are not immutable. We have to get rid of that.

## TODOs

This issue is mainly here to:

 - [x] collect thoughts on this approach
 - [ ] find downsides in this approach
 - [ ] identify components that retain state
 - [ ] track PRs and issues about making those components stateless or immutable

## Identified components with problems so far

 - [ ] the router component instantiates different routes depending on request type
 - [ ] the view manager is instantiated depending on the request type
 - [ ] view helpers are not stateless (make view helper manager un-shared?)
 - [ ] request, response and mvcevent should not be stored in the application object
 - [ ] ...

I don't yet have a list of components that retain state, but so far I can tell that a lot of plugins in the view layer keep an internal state, as well as the `Request` object (which is a service, see [this page again](https://igor.io/2013/03/31/stateless-services.html) on why we should NOT do that!), the `Response` object, the `MvcEvent` and other stuff that should not be available via getters.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
