### ISSUE TITLE
[ZF3][RFC] Refactoring the Hostname validator

### ISSUE THREAD

**Issue by moderndeveloperllc** [zendframework/zendframework#7312]
It looks like I may have time available to do a long needed refactoring of the Hostname validator. I would like feedback from the core contributors when it comes to the desirability of certain options.

### Why is a refactoring needed? ###
* Length and positional validations are currently being done on the composed Unicode encoding of domains and TLDs. All length requirements are based on the ACE of the name.
* Not nearly enough IDN domain info. There are [many, many more](http://www.iana.org/domains/idn-tables) domain tables. This brings into question the current system for storing this info.
* The class currently assumes PCRE Unicode support without testing for it.
* There is currently a homegrown function that replicates `idn_to_utf8()` functionality, but none for `idn_to_ascii()`.
* There is no way to specify a language restriction for a TLD (Only check Icelandic characters for this .com domain)
* There is no option to see if the hostname actually _exists_ via something like `checkdnsrr()`.

#### I propose that this validator either: ####
  a) Me moved over to the `Zend\I18n\Validator` namespace so we can be assured of the `intl` extension.

  b) Split the class - Have a non-IDN version in `Zend\Validator` for use by developers who don't deal with IDN domains, and a version in `Zend\I18n\Validator` that includes all the IDN files, manipulation, etc.

or

  c) Write `intl`-checking logic into a class in `Zend\Validator`. If we don't have that or PCRE Unicode support, only check non-IDN domains and characters.

The first option has the value of being DRY'er by not replicating much of the same code. With ZF3 trying to remove inter-module dependancies, I'm not sure you would want to add `Zend\Validator` as a requirement to the `Zend\I18n` module. The second option would probably result in faster code for a majority of users by not including lots of logic and data for every domain check. For instance, if no language is specified, you could be checking upwards of 100 character sets for domains in the .com TLD. The third option would have code that is a bit more complex, and and you are bringing `Zend\I18n\Validator`-type functions into the `Zend\Validator` namespace.

The downside of option a) is that there is now another module to add (Zend\I18n) for any dev who wants to check hostnames - even if they are not doing any I18n. The issue with b) is that it isn't DRY, and will require more maintenance, testing, etc.

### Questions for Core Developers ###
- [ ] Are these valid reasons to take the time and rewrite everything, or is the current class structure fine?
- [ ] Do I split the Hostname validation code into two classes, move it into `Zend\I18n\Validator`, or try and write `intl`-checking logic into a class in `Zend\Validator`?
- [ ] Would you want a separate HostnameExists class for `checkdnsrr()`-style checking, or as an option to the `Hostname` class?
- [ ] Any thoughts on data storage? I know that loading files from the harddrive is slow, but I don't think we can realistically stuff this class with the > 1MB of data that all these code tables contain.

### TODOs: ###
- [ ] Decide to split or not split the class
- [ ] Figure out how to store IDN information
- [ ] Write tests
- [ ] Code the validation logic for the class (or two!)
- [ ] Add (optional) caching logic for data files.
- [ ] Add new `Zend\Validator\HostnameExists` class to check for existing records?

It should be noted that this validator can only check if the domain/IP/URI is properly formatted with the correct characters. It will not check to see if the domain is actually _permissible_ by the TLD registrar. Many gTLD registrars have rules that are beyond the scope of any general validator. For instance, many IDN registrars will not allow you to register domains that have [codepoints that are variants of existing domains](http://www.donuts.co/policies/idn/).

[Edit to add permissibility paragraph at bottom -MDG]

**Comment by moderndeveloperllc** [comment]
ping @DASPRiD, @Ocramius

**Comment by moderndeveloperllc** [comment]
@weierophinney Should I pursue this, or am I just looking to do something that will be invalidated by other ZF3 changes in teh future?

**Comment by moderndeveloperllc** [comment]
@DASPRiD, @Ocramius is this something I should pursue? Don't want to spend a big chunk of time to do this if it's already being done.

**Comment by RalfEggert** [comment]
Should be marked for ZF3 milestone, shouldn't it?

**Comment by weierophinney** [comment]
@moderndeveloperllc I'd open new PRs against:

- https://github.com/zendframework/zend-validator
- https://github.com/zendframework/zend-i18n

and discuss in those. I personally prefer having all the validators in one package, with defined *optional* dependencies specified for validators that need them (I'd argue the same for filters and other plugins, too); when I look for a validator, I'm not looking in zend-i18n, I'm looking in zend-validator.

Other than that, I think the refactor seems reasonable.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-validator/issues/98
